### Problem Descripition 

In 2012, URL shortening service Bitly partnered with the US government website USA.gov to provide a feed of anonymous data gathered from users who shorten links ending with .gov or .mil.

The text file comes in JSON format and here are some keys and their description. They are only the most important ones for this task.

|key| description |
|---|-----------|
| a|Denotes information about the web browser and operating system|
| tz | time zone |
| r | URL the user come from |
| u | URL where the user headed to |
| t | Timestamp when the user start using the website in UNIX format |
| hc | Timestamp when user exit the website in UNIX format |
| cy | City from which the request intiated |
| ll | Longitude and Latitude |

In the cell, I tried to provide some helper code for better understanding and clearer vision

-**HINT**- Those lines of code may be not helping at all with your task.

In [30]:
import json 
import pandas as pd

records = [json.loads(line) for line in open('usa.gov_click_data.json')]
records_df = pd.DataFrame(records)
records_df.head()

,_heartbeat_,a,al,c,cy,g,gr,h,hc,hh,kw,l,ll,nk,r,t,tz,u
0,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"en-US,en;q=0.8",US,Danvers,A6qOVH,MA,wfLQtf,1.331823e+09,1.usa.gov,NaN,orofrog,"[42.576698, -70.954903]",1.0,http://www.facebook.com/l/7AQEFzjSi/1.usa.gov/...,1.331923e+09,America/New_York,http://www.ncbi.nlm.nih.gov/pubmed/22415991
1,NaN,GoogleMaps/RochesterNY,NaN,US,Provo,mwszkS,UT,mwszkS,1.308262e+09,j.mp,NaN,bitly,"[40.218102, -111.613297]",0.0,http://www.AwareMap.com/,1.331923e+09,America/Denver,http://www.monroecounty.gov/etc/911/rss.php
2,NaN,Mozilla/4.0 (Windows NT 6.1; MSIE 8.0; Windows...,en-US,US,Washington,xxr3Qb,DC,xxr3Qb,1.331920e+09,1.usa.gov,NaN,bitly,"[38.9007, -77.043098]",1.0,http://t.co/03elZC4Q,1.331923e+09,America/New_York,http://boxer.senate.gov/en/press/releases/0316...
3,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,pt-br,BR,Braz,zCaLwp,27,zUtuOu,1.331923e+09,1.usa.gov,NaN,alelex88,"[-23.549999, -46.616699]",0.0,direct,1.331923e+09,America/Sao_Paulo,http://apod.nasa.gov/apod/ap120312.html
4,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"en-US,en;q=0.8",US,Shrewsbury,9b6kNl,MA,9b6kNl,1.273672e+09,bit.ly,NaN,bitly,"[42.286499, -71.714699]",0.0,http://www.shrewsbury-ma.gov/selco/,1.331923e+09,America/New_York,http://www.shrewsbury-ma.gov/egov/gallery/1341...

In [31]:
records_df = records_df[['a', 'r', 'u', 'cy', 'll', 'tz', 't', 'hc']]
records_df.shape

(3560, 8)

In [32]:
records_df.isna().sum()

a     120
r     120
u     120
cy    641
ll    641
tz    120
t     120
hc    120
dtype: int64

In [33]:
records_df = records_df.dropna()

In [34]:
records_df.isna().sum()

a     0
r     0
u     0
cy    0
ll    0
tz    0
t     0
hc    0
dtype: int64

In [35]:
def extract_os(a):
    a = str(a)
    from_i = a.find('(')
    if from_i == -1:
        return ''
    to_i = a.find(';', from_i)
    if to_i == -1:
        to_i = a.find(')', from_i)
    #print(to_i)
    os = a[from_i+1:to_i]
    return os



def Make_URL_Short(URL):
    URL = str(URL)
    from_i = URL.find('/')
    if from_i == -1:
        return URL
    to_i = URL.find('/', from_i+2)
    short_url = URL[from_i+2:to_i]
    return short_url

In [36]:
Make_URL_Short('http://www.ncbi.nlm.nih.gov/pubmed/22415991	')

'www.ncbi.nlm.nih.gov'

In [37]:
#records_df.insert(0, 'web_browser', records_df['a'].apply(lambda x : str(x).split(' ')[0]))
#records_df.insert(1, 'operating_system', records_df['a'].apply(extract_os))

records_df['web_browser'] = records_df['a'].apply(lambda x : str(x).split(' ')[0])
records_df['operating_system'] = records_df['a'].apply(extract_os)

#records_df.drop(['a'], axis=1, inplace=True)

records_df['r'] = records_df['r'].apply(Make_URL_Short)
records_df['u'] = records_df['u'].apply(Make_URL_Short)
records_df.sample(5)

,a,r,u,cy,ll,tz,t,hc,web_browser,operating_system
1027,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.1...,t.co,www.fda.gov,Philadelphia,"[40.037498, -75.145401]",America/New_York,1.331924e+09,1.331924e+09,Mozilla/5.0,Windows NT 5.1
1038,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1...,t.co,www.nasa.gov,Mexico,"[19.4342, -99.138603]",America/Mexico_City,1.331924e+09,1.331922e+09,Mozilla/5.0,Windows NT 6.1
2527,Mozilla/5.0 (Linux; U; Android 2.3.5; en-gb; H...,t.co,www.bls.gov,Belfast,"[54.583302, -5.9333]",Europe/London,1.331926e+09,1.265639e+09,Mozilla/5.0,Linux
3006,Mozilla/5.0 (Windows NT 6.1; MSIE 9.0; Windows...,americasgreatoutdoors.tumblr.com,www.nps.gov,Chula Vista,"[32.636101, -117.0532]",America/Los_Angeles,1.331926e+09,1.331837e+09,Mozilla/5.0,Windows NT 6.1
1977,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,www.facebook.com,www.nasa.gov,Brandon,"[27.929501, -82.298698]",America/New_York,1.331925e+09,1.331923e+09,Mozilla/5.0,Windows NT 6.1

In [38]:
def extract_longitude(ll):
    ll = ll.split(',')
    if len(ll)>0:
        return ll[0][1:]
    else:
        return ''

def extract_latitude(ll):
    ll = ll.split(',')
    if len(ll)>1:
        return ll[1][1:-1]
    else:
        return ''

In [39]:
#records_df.fillna('', inplace=True)
#records_df['longitude'] = records_df['ll'].astype(str).apply(extract_longitude)
#records_df['latitude'] = records_df['ll'].astype(str).apply(extract_latitude)

records_df['longitude'] = records_df['ll'].astype(str).apply(lambda x : x.split(',')[0][1:] if x!='' else '')
records_df['latitude'] = records_df['ll'].astype(str).apply(lambda x : x.split(',')[1][1:-1] if x!='' else '')

In [40]:
records_df['t'] = pd.to_datetime(records_df['t'], unit='s') 
records_df['hc'] = pd.to_datetime(records_df['hc'], unit='s')

In [41]:
import numpy as np
np.max(records_df['hc'] - records_df['t'])

Timedelta('-1 days +23:59:50')

In [42]:
records_df.drop(['ll'], axis=1, inplace=True)
records_df.rename(columns={'r':'from_url', 'u':'to_url', 'cy':'city', 'tz':'time_zone', 't':'time_out', 'hc':'time_in'}, inplace=True)
records_df.sample(10)

,a,from_url,to_url,city,time_zone,time_out,time_in,web_browser,operating_system,longitude,latitude
3046,Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US...,direct,www.usa.gov,Madrid,Europe/Madrid,2012-03-16 19:29:36,2012-02-01 15:57:25,Mozilla/5.0,Windows,40.400002,-3.6833
2413,Mozilla/4.0 (Windows NT 6.1; MSIE 8.0; Windows...,t.co,www.fda.gov,Highland Park,America/Chicago,2012-03-16 19:18:24,2012-03-16 15:42:18,Mozilla/4.0,Windows NT 6.1,42.188999,-87.806297
3272,Mozilla/5.0 (Windows NT 6.1; rv:10.0.2) Gecko/...,t.co,www.usaid.gov,Houston,America/Chicago,2012-03-16 19:34:21,2012-03-16 19:19:41,Mozilla/5.0,Windows NT 6.1,29.7346,-95.416
3428,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_8)...,nix.nasa.gov,ntrs.nasa.gov,Sstat,Europe/Paris,2012-03-16 19:37:52,2012-03-16 11:14:25,Mozilla/5.0,Macintosh,48.266701,7.45
1415,Mozilla/5.0 (Windows NT 6.1; rv:10.0.2) Gecko/...,direct,www.nysdot.gov,Brooklyn,America/New_York,2012-03-16 19:02:09,2011-10-25 17:25:56,Mozilla/5.0,Windows NT 6.1,40.583302,-73.924004
2366,Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKi...,t.co,www.dol.gov,Zeeland,America/New_York,2012-03-16 19:17:42,2010-04-21 16:02:11,Mozilla/5.0,Windows NT 6.0,42.8554,-85.971397
1424,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3)...,t.co,www.kingcounty.gov,Seattle,America/Los_Angeles,2012-03-16 19:02:17,2012-03-02 23:34:57,Mozilla/5.0,Macintosh,47.631901,-122.296799
2284,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2)...,www.huffingtonpost.com,www.cia.gov,Bridgeport,America/New_York,2012-03-16 19:16:15,2009-05-10 14:07:55,Mozilla/5.0,Windows NT 6.1,41.2094,-73.211601
3338,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,t.co,www.healthcare.gov,Washington,America/New_York,2012-03-16 19:35:44,2012-03-16 17:24:51,Mozilla/5.0,Macintosh,38.9007,-77.043098
1793,GoogleMaps/RochesterNY,www.AwareMap.com,www.monroecounty.gov,Provo,America/Denver,2012-03-16 19:07:47,2011-06-16 22:13:13,GoogleMaps/RochesterNY,,40.218102,-111.613297

In [44]:
records_df.drop(['a'], axis=1, inplace=True)
records_df.head()

,from_url,to_url,city,time_zone,time_out,time_in,web_browser,operating_system,longitude,latitude
0,www.facebook.com,www.ncbi.nlm.nih.gov,Danvers,America/New_York,2012-03-16 18:40:47,2012-03-15 14:48:38,Mozilla/5.0,Windows NT 6.1,42.576698,-70.954903
1,www.AwareMap.com,www.monroecounty.gov,Provo,America/Denver,2012-03-16 18:40:49,2011-06-16 22:13:13,GoogleMaps/RochesterNY,,40.218102,-111.613297
2,t.co,boxer.senate.gov,Washington,America/New_York,2012-03-16 18:40:50,2012-03-16 17:45:41,Mozilla/4.0,Windows NT 6.1,38.9007,-77.043098
3,direct,apod.nasa.gov,Braz,America/Sao_Paulo,2012-03-16 18:40:49,2012-03-16 18:37:48,Mozilla/5.0,Macintosh,-23.549999,-46.616699
4,www.shrewsbury-ma.gov,www.shrewsbury-ma.gov,Shrewsbury,America/New_York,2012-03-16 18:40:51,2010-05-12 13:53:31,Mozilla/5.0,Windows NT 6.1,42.286499,-71.714699

In [45]:
records_df.to_csv('usa.gov_click_data_clean.csv', index=False)

## Required

Write a script can transform the JSON files to a DataFrame and commit each file to a sparete CSV file in the target directory and consider the following:

All CSV files must have the following columns
- web_browser
        The web browser that has requested the service
- operating_sys
        operating system that intiated this request
- from_url

        The main URL the user came from

    **note**:

    If the retrived URL was in a long format `http://www.facebook.com/l/7AQEFzjSi/1.usa.gov/wfLQtf`

     make it appear in the file in a short format like this `www.facebook.com`
     
    
- to_url

       The same applied like `to_url`
   
- city

        The city from which the the request was sent
    
- longitude

        The longitude where the request was sent
- latitude

        The latitude where the request was sent

- time_zone
        
        The time zone that the city follow
        
- time_in

        Time when the request started
- time_out
        
        Time when the request is ended
        
        
**NOTE** :

Because that some instances of the file are incomplete, you may encouter some NaN values in your transforamtion. Make sure that the final dataframes have no NaNs at all.